language: c++
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - cmake
    - cmake-data


before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50
compiler:
  - g++

script:
  - mkdir build
  - cd build
  - cmake ../uni10 && make
