language: c++

sudo: required
dist: trusty
branches: 
  only: 
    - travis
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    packages:
    # install toolchains
    - libhdf5
    - libhdf5-dev


#before_install:
compiler:
  - g++
  - clang

script:
  - mkdir build
  - cd build
  - cmake ../uni10 && make
